services:
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    restart: always
    volumes:
      - zookeeper_data:/data
      - zookeeper_logs:/logs
    expose:
      - 2181
    networks:
      - kafka-nodejs-test

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    volumes:
      - kafka_data:/kafka
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://:9093
      ALLOW_PLAINTEXT_LISTENER: YES
    depends_on:
      - zookeeper
    networks:
      - kafka-nodejs-test

networks:
  kafka-nodejs-test:
    driver: bridge
volumes:
  kafka_data:
  zookeeper_logs:
  zookeeper_data:
